trigger:
  branches:
    include:
      - master
      - main
  tags:
    include:
      - '*'
  
pr:
  branches:
    include:
      - master
      - main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  NUGET_PLUGIN_HANDSHAKE_TIMEOUT_IN_SECONDS: 30
  NUGET_PLUGIN_REQUEST_TIMEOUT_IN_SECONDS: 30

steps:
  - bash: |
      VERSION=`git describe --tags --dirty=M 2> /dev/null | sed -e 's/[^/]*\///g' -e 's/-/_/g'`
      echo "##vso[build.updatebuildnumber]${VERSION}+${BUILD_BUILDID}"
      echo "##vso[task.setvariable variable=version;isOutput=true]${VERSION}"
    displayName: Update build name
    condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Manual'))
    
  - task: Bash@3
    displayName: Set as release build
    name: release
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    inputs:
      targetType: inline
      script: |
        if [ -n "$(awk -F. '$0 ~ /^refs\/tags\/[0-9]+\.[0-9]+\.[0-9]+$/ { print $0 }' <<< ${BUILD_SOURCEBRANCH})" ] ; then
          echo "##vso[task.setvariable variable=release;isOutput=true]true"
          echo "##vso[build.addbuildtag]Release"
        fi

  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      
  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:DeployDefaultTarget=WebPublish /p:SkipInvalidConfigurations=true /p:PublishUrl="$(build.artifactStagingDirectory)\BypassConfiguration"'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
  
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: | 
        Move-Item "$(Build.ArtifactStagingDirectory)\BypassConfiguration\Web.config" "$(Build.ArtifactStagingDirectory)\"         
        Copy-Item "$(Build.ArtifactStagingDirectory)\BypassConfiguration\public" "$(Build.ArtifactStagingDirectory)\public"
        Copy-Item "$(Build.ArtifactStagingDirectory)\BypassConfiguration\bin" "$(Build.ArtifactStagingDirectory)\bin"
        Rename-Item "$(Build.ArtifactStagingDirectory)\BypassConfiguration" "BPCM"
  
  - publish: '$(build.artifactStagingDirectory)'
    artifact: BPCM